# Generated by Django 5.0.6 on 2024-06-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=46, verbose_name='Название породы')),
                ('size', models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=6)),
                ('friendliness', models.IntegerField(choices=[(1, '1 - min'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - max')], default=3, help_text='Уровень дружелюбности от 1 (Минимально дружелюбный) до 5 (Максимально дружелюбный).', verbose_name='Дружелюбность')),
                ('trainability', models.IntegerField(choices=[(1, '1 - min'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - max')], default=3, help_text='Уровень обучаемости от 1 (не обучаемый) до 5 (легкообучаемый)', verbose_name='Обучаемость')),
                ('shedding_amount', models.IntegerField(choices=[(1, '1 - min'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - max')], default=3, help_text='Уровень линьки шерсти от 1 (не линяет) до 5 (все вокруг в шерсти)', verbose_name='Уровень линьки')),
                ('exercise_needs', models.IntegerField(choices=[(1, '1 - min'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - max')], default=3, help_text='Уровень необходимых тренировок от 1 (тренировки необязательны) до 5 (необходимы постоянно)', verbose_name='Уровень необходимых тренировок')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=46, verbose_name='Имя собаки')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(max_length=20, verbose_name='Гендер')),
                ('color', models.CharField(max_length=25, verbose_name='Цвет')),
                ('favorite_food', models.CharField(max_length=80, verbose_name='Любимая еда')),
                ('favorite_toy', models.CharField(max_length=52, verbose_name='Любимая игрушка')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='api.breed')),
            ],
        ),
    ]
